--- 
title: "Good practices in bioinformatic or computational biology projects"
author: "Yang Cao"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
github-repo: yiluheihei/codestyle
---

# About {-}

Welcome!

Good practices in bioinformatic or computational biology projects.

Bioinformatic or computational biology projects need to follow the same
practices as lab projects and notebooks, with organized data, documented steps,
the project structured for reproducibility, and the consistent code style.

## Project Organization {-}

It is generally a good idea to store all of the files relevant to one project
under a common root directory. And organizing the files that make up a project 
in a logical and consistent directory structure will help you and others keep
track of them.

The recommendations are drawn from:

Wilson, Greg, et al. "Good enough practices in scientific computing." PLoS computational biology 13.6 (2017): e1005510.

## Code style {-}

Write code in a consistent style will make it easier to maintain, and easier
for collaborators to understand. Code is more often read than written, and code
style can also have a great impact on the readability of your code

The style guides here are fundamentally opinionated, but not too opinionated. 
And many decisions are arbitrary, any suggestions are welcome.

The bash is derived from 
[Google's shell style guide](https://google.github.io/styleguide/shellguide.html); 
python code style is derived from 
[Google's python style guide](https://www.python.org/dev/peps/pep-0008/) and 
[PEP 8 style guide for python](https://www.python.org/dev/peps/pep-0008/); and 
the R code style is drived from 
[Tidyverse Style Guide](https://style.tidyverse.org/).

**If you’re modifying existing files, you should follow the style that’s already 
in the files.**

    Do what Romans do in Rome.